In [1]:
import numpy as np
import pandas as pd

In [2]:
text = ['This is a line', 
       'This is another line',
       'Completely different line']

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv = CountVectorizer(stop_words='english')

In [15]:
sparse_matrix = cv.fit_transform(text)

In [16]:
sparse_matrix.todense() # Memory efficient way to store this matrix. Don't call it when it is too big!

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]])

In [17]:
cv.vocabulary_ # The dictionary that we manually created on the previous lecture.

{'line': 2, 'completely': 0, 'different': 1}

In [18]:
from sklearn.feature_extraction.text import TfidfTransformer

In [19]:
tfidf = TfidfTransformer()

In [20]:
results = tfidf.fit_transform(sparse_matrix) # BOW ---> TF_IDF

In [21]:
results.todense()

matrix([[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.65249088, 0.65249088, 0.38537163]])

#### If you want to do the vectorization and Tf-idf conversion in one single step you can use the following:

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
tv = TfidfVectorizer()

In [24]:
tv_results = tv.fit_transform(text)

In [26]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])