In [1]:
#Slicing through numpy arrays:
import numpy as np

arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
arr[:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [5]:
# To make a copy of the array:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [6]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [8]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])